package com.nameless.efb.domain.gauge

/**
 * Annunciator alert types generated by the gauge panel monitoring logic.
 *
 * Alerts trigger visual highlights and (where supported) haptic / audio
 * feedback via [AlertManager].
 */
enum class AlertType {
    OIL_TEMP_HIGH,
    OIL_PRESS_LOW,
    FUEL_LOW,          // less than 30 min endurance at current flow
    FUEL_IMBALANCE,    // more than 5 kg difference between tanks
    VOLTAGE_LOW,       // bus volts < 13.0 V while engine running
    GYRO_UNRELIABLE,   // suction < 4.5 inHg
}
